sudo: true
dist: trusty
language: node_js
cache:
  directories:
    - $HOME/.yarn-cache
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '6.8.1'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - npm i -g npm@3.10.9
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: yarn
script:
  - yarn run test:once:ci
  - yarn run build:lib
after_success:
  - npm run semantic-release
