sudo: true
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '6.8.1'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
before_install:
  - npm i -g npm@3.10.9
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
before_script:
  - npm prune
script:
  - npm run test:once:ci
  - npm run e2e
  - npm run build:lib
after_success:
  - npm run semantic-release
